### ISSUE TITLE
CIMI does not allow datetimes with non-fractional seconds

### ISSUE THREAD

**Issue by rosogon** [mF2C/cimi#25]
E.g., trying to create an agreement:

```
{
    "id": "a02",
    "name": "Agreement 02",
    "state": "stopped",
    "details":{
        "id": "a02",
        "type": "agreement",
        "name": "Agreement 02",
        "provider": { "id": "mf2c", "name": "mF2C Platform" },
        "client": { "id": "c02", "name": "A client" },
        "creation": "2018-01-16T17:09:45Z",
        "expiration": "2019-01-17T17:09:45Z",
        "guarantees": [
            {
                "name": "TestGuarantee",
                "constraint": "[test_value] < 10"
            }
        ]
    }
}
```

results in

```
resource does not satisfy defined schema:
-- Spec failed --------------------

  {:updated ...,
   [...]
    :creation \"2018-01-16T17:09:45Z\",
              ^^^^^^^^^^^^^^^^^^^^^^
   [...]
   :resourceURI ...}

should satisfy

  as-datetime
```

**Comment by cjdcordeiro** [comment]
@rosogon this is not a bug. This is the expected behavior.

The timestamp format is defined at https://github.com/slipstream/SlipStreamServer/blob/5a6456d9100d9b147427aaa94ef11bfffb841647/cimi/src/com/sixsq/slipstream/ssclj/resources/common/utils.clj#L98.

You can see it is a `date-time`, so it expects milliseconds. Changing this to no-milli would cause a backward incompatibility in many other places

**Comment by rosogon** [comment]
I can understand that you will not fix it because of backwards compatibility, but this is not expected behavior. It is my first time I am obliged to use milliseconds in a datetime. I also see that the CIMI specification (at least v2) defines datetimes as xs:dateTime (consistent with ISO8601), which does not mandate fractional seconds.

To clarify, Go std library removes the fractional seconds part if equal to zero on serialization. I will not hack the datetime serialization to make it CIMI compatible. So I guess we will have errors on this from time to time.

**Comment by cjdcordeiro** [comment]
ISO8601 does mandate the use of fractional time elements, but with the nuance that the number of decimal digits is up to the implementation, so in fact, it seems that dateTimes in Go are implemented, by default, to set the amount of fractional digits to 0. 

Check Python for example, and the standard `datetime` library will give you 6 decimal digits.

All of this is configurable however, so it sounds really odd that you cannot set a `formatter` in Go, to force-include the milliseconds.

Besides, you'll be a very lucky guy if you can get ask for a dateTime and get H:M:S.000 :)

**Comment by rosogon** [comment]
Datetimes without fractional seconds are iso8601 valid, so fractional time elements are not mandatory. I cannot get the spec, but according to Wikipedia: "Decimal fractions *may* be added to any of the three time elements".

**Comment by cjdcordeiro** [comment]
yes, mandate might have been the wrong wording. Bottom line is that, ISO8601 allows fractional numbers with 0 digits...so 0 fractional digits = no decimals. 

Then it is a matter of implementation. In CIMI this is implemented to a 3 digit resolution so that we can order by date, lexically 

If you want no-ms, then I suggest you don't use CIMI's default timestamp, but create your own instead. 
Example: 
```
(require '[clj-time.format :as f])
(f/parse (f/formatters :date-time-no-ms) "2019-01-17T17:09:45Z")
```
