### ISSUE TITLE
integrate dc and dc wrapper with CIMI, through mvn

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/cimi#42]
needed by mF2C/cimi#30
needed by mF2C/cimi#32

**Comment by rosogon** [comment]
Anna: for all the functions that CIMI sends to dataClay (create, read, update, delete), we are receiving the type in the "CIMI format" (i.e. "device", "device-dynamic", etc). However, for the query the type we receive is in the format "Device", "DeviceDynamic", etc, while we are expecting the same as for the rest of functions. This still works (by chance) in most cases, that's why some queries work (and that's why it was hard to find). But for those resources that have links to other resources, the query fails

**Comment by cjdcordeiro** [comment]
dcproxy will be kept. New versions are here: https://github.com/mF2C/cimi/blob/master/_demo/docker-compose.yml
